/* global window, document */
const api=window.migrationUi;const $=(id)=>document.getElementById(id);const fields={backups:$('backups'),destination:$('destination'),mapping:$('mapping'),report:$('report')};let analyzedSignature='';let lastReportFile='';
const signature=()=>JSON.stringify({b:fields.backups.value,d:fields.destination.value,m:fields.mapping.value,u:$('missing-users').checked,a:$('missing-attachments').checked});
const invalidate=()=>{if(analyzedSignature&&analyzedSignature!==signature()){$('apply').disabled=true;$('state').textContent='As opções mudaram. Analise novamente.'}};
Object.values(fields).forEach((field)=>field.addEventListener('change',invalidate));$('missing-users').addEventListener('change',invalidate);$('missing-attachments').addEventListener('change',invalidate);
document.querySelectorAll('[data-pick]').forEach((button)=>button.addEventListener('click',async()=>{const kind=button.dataset.pick;const fn={backups:api.pickBackups,destination:api.pickDestination,mapping:api.pickMapping,report:api.pickReport}[kind];const value=await fn();if(value){fields[kind].value=value;invalidate()}}));
document.querySelector('[data-clear="mapping"]').addEventListener('click',()=>{fields.mapping.value='';invalidate()});
api.onOutput((text)=>{const log=$('log');if(log.textContent==='Aguardando análise…')log.textContent='';log.textContent+=text;log.scrollTop=log.scrollHeight});
$('clear-log').addEventListener('click',()=>{$('log').textContent=''});$('open-report').addEventListener('click',()=>api.openPath(lastReportFile));
const input=(apply)=>({backupsDir:fields.backups.value,relayDataDir:fields.destination.value,mappingFile:fields.mapping.value,reportFile:fields.report.value,allowMissingUsers:$('missing-users').checked,allowMissingAttachments:$('missing-attachments').checked,apply});
const issues=(report)=>{const box=$('issues');box.textContent='';const errors=Array.isArray(report?.errors)?report.errors:[];const warnings=Array.isArray(report?.warnings)?report.warnings:[];if(!errors.length&&!warnings.length){const p=document.createElement('p');p.className='issue ok';p.textContent='Nenhum conflito impeditivo encontrado.';box.append(p)};for(const message of errors){const p=document.createElement('p');p.className='issue error';p.textContent=message;box.append(p)}for(const message of warnings){const p=document.createElement('p');p.className='issue warning';p.textContent=message;box.append(p)}};
const render=(result,apply)=>{const report=result.report||{};lastReportFile=result.reportFile||'';$('results').classList.remove('hidden');$('open-report').classList.toggle('hidden',!lastReportFile);const counts=report.counts||{};$('metrics').innerHTML='';for(const [label,key] of [['Backups','backups'],['Usuários','users'],['Mensagens','messages'],['Anexos','attachments']]){const card=document.createElement('div');card.className='metric';const strong=document.createElement('strong');strong.textContent=String(counts[key]??0);const span=document.createElement('span');span.textContent=label;card.append(strong,span);$('metrics').append(card)}issues(report);if(apply&&result.ok){$('result-summary').textContent='Migração concluída. Preserve o rollback até validar o Relay.';$('apply').disabled=true;$('state').textContent='Migração concluída.'}else{$('result-summary').textContent=result.ok?'Análise concluída. Revise os totais e avisos antes de aplicar.':'A análise encontrou erros que precisam ser resolvidos.';$('apply').disabled=!result.ok||Boolean(report.errors?.length);$('state').textContent=result.ok?'Análise concluída.':'Falha na análise.'}};
const run=async(apply)=>{const button=apply?$('apply'):$('analyze');button.disabled=true;$('analyze').disabled=true;$('state').textContent=apply?'Aplicando migração…':'Analisando backups…';try{const result=await api.run(input(apply));if(result?.canceled){$('state').textContent='Migração cancelada.';return}render(result,apply);if(!apply&&result.ok&&!result.report?.errors?.length)analyzedSignature=signature()}catch(error){$('state').textContent=error?.message||String(error);$('apply').disabled=true}finally{$('analyze').disabled=false;if(!apply)$('apply').disabled=!(analyzedSignature===signature())}};
$('analyze').addEventListener('click',()=>run(false));$('apply').addEventListener('click',()=>{if(analyzedSignature!==signature()){invalidate();return}run(true)});
